### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by cqsnove** [qiqihaer/3DSSD-pytorch#3]
Traceback (most recent call last):
  File "lib/core/trainer.py", line 16, in <module>
    from core.config import cfg, cfg_from_file, cfg_from_list, assert_and_infer_cfg
  File "/mnt/disk/home1/cqs/3DSSD-pytorch/lib/core/config.py", line 16, in <module>
    from lib.utils.collections import AttrDict
ModuleNotFoundError: No module named 'lib'

Can you work out this problem? Thanks!

**Comment by zye1996** [comment]
> Traceback (most recent call last):
> File "lib/core/trainer.py", line 16, in
> from core.config import cfg, cfg_from_file, cfg_from_list, assert_and_infer_cfg
> File "/mnt/disk/home1/cqs/3DSSD-pytorch/lib/core/config.py", line 16, in
> from lib.utils.collections import AttrDict
> ModuleNotFoundError: No module named 'lib'
> 
> Can you work out this problem? Thanks!

Hi, try run ```python -m lib.core.trainer``` with extra arguments

**Comment by nicholaswhf** [comment]
hi, try run `export PYTHONPATH=$PYTHONPATH:/mnt/disk/home1/cqs/3DSSD-pytorch/lib`
